// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_DestinationInfo_screen_init(void)
{
ui_DestinationInfo = lv_obj_create(NULL);
lv_obj_clear_flag( ui_DestinationInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_DestinationInfo);
lv_img_set_src(ui_Image1, &ui_img_ic_depart_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image1, 0 );
lv_obj_set_y( ui_Image1, -109 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Image1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Image1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_NextTurnDistance = lv_label_create(ui_DestinationInfo);
lv_obj_set_width( ui_NextTurnDistance, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_NextTurnDistance, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_NextTurnDistance, 0 );
lv_obj_set_y( ui_NextTurnDistance, 4 );
lv_obj_set_align( ui_NextTurnDistance, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_NextTurnDistance,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_NextTurnDistance, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_NextTurnDistance,"300m");
lv_obj_set_style_text_font(ui_NextTurnDistance, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NextTurnInstruction = lv_label_create(ui_DestinationInfo);
lv_obj_set_width( ui_NextTurnInstruction, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_NextTurnInstruction, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_NextTurnInstruction, 0 );
lv_obj_set_y( ui_NextTurnInstruction, 59 );
lv_obj_set_align( ui_NextTurnInstruction, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_NextTurnInstruction,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_NextTurnInstruction, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_NextTurnInstruction,"Take Left");
lv_obj_set_style_text_font(ui_NextTurnInstruction, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_DestinationInfo);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 0 );
lv_obj_set_y( ui_Label3, 146 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Label3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Label3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_Label3,"15min/9km");
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

}
