// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_HomeScreen_screen_init(void)
{
ui_HomeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Message = lv_label_create(ui_HomeScreen);
lv_obj_set_width( ui_Message, lv_pct(80));
lv_obj_set_height( ui_Message, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Message, LV_ALIGN_CENTER );
lv_label_set_text(ui_Message,"No Navigation Started");
lv_obj_set_style_text_align(ui_Message, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Message, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

}
