// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_NavigationScreen_screen_init(void)
{
ui_NavigationScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_NavigationScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DirectionImage = lv_img_create(ui_NavigationScreen);
lv_img_set_src(ui_DirectionImage, &ui_img_ic_depart_png);
lv_obj_set_width( ui_DirectionImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DirectionImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DirectionImage, 0 );
lv_obj_set_y( ui_DirectionImage, -131 );
lv_obj_set_align( ui_DirectionImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DirectionImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_DirectionImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_NextTurnDistance = lv_label_create(ui_NavigationScreen);
lv_obj_set_width( ui_NextTurnDistance, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_NextTurnDistance, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_NextTurnDistance, 0 );
lv_obj_set_y( ui_NextTurnDistance, -22 );
lv_obj_set_align( ui_NextTurnDistance, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_NextTurnDistance,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_NextTurnDistance, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_NextTurnDistance,"300m");
lv_obj_set_style_text_font(ui_NextTurnDistance, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Instruction = lv_label_create(ui_NavigationScreen);
lv_obj_set_width( ui_Instruction, lv_pct(80));
lv_obj_set_height( ui_Instruction, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Instruction, 0 );
lv_obj_set_y( ui_Instruction, 53 );
lv_obj_set_align( ui_Instruction, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Instruction,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Instruction, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_Instruction,"Turn right onto XYZ road");
lv_obj_set_style_text_align(ui_Instruction, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Instruction, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RemainingTime = lv_label_create(ui_NavigationScreen);
lv_obj_set_width( ui_RemainingTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RemainingTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RemainingTime, 0 );
lv_obj_set_y( ui_RemainingTime, 155 );
lv_obj_set_align( ui_RemainingTime, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_RemainingTime,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_RemainingTime, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_RemainingTime,"15min");
lv_obj_set_style_text_align(ui_RemainingTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RemainingTime, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RemainingDistance = lv_label_create(ui_NavigationScreen);
lv_obj_set_width( ui_RemainingDistance, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RemainingDistance, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RemainingDistance, 0 );
lv_obj_set_y( ui_RemainingDistance, 189 );
lv_obj_set_align( ui_RemainingDistance, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_RemainingDistance,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_RemainingDistance, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_RemainingDistance,"9km");
lv_obj_set_style_text_align(ui_RemainingDistance, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RemainingDistance, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

}
